#!/bin/sh

set -e
: ${CLUSTER_LANDING_PAGE_ENV_VERSION?"Must set CLUSTER_LANDING_PAGE_ENV_VERSION"}
: ${CLUSTER_LOGIN_URL_OIDCIDP?"Must set CLUSTER_LOGIN_URL_OIDCIDP"}
: ${CLUSTER_LANDING_PAGE_SECONDARY_ENV_VERSION?"Must set CLUSTER_LANDING_PAGE_SECONDARY_ENV_VERSION"}

yasha -o /usr/share/nginx/html/index.html index.html.j2
