site_name: Rahti user guide
pages:
  - Home: index.md
  - Introduction:
    - Background: introduction/background.md
    - Getting access: introduction/access.md
  - Usage:
    - Getting started: usage/getting_started.md
  - External documentation: ext_docs.md
theme: readthedocs
extra_css:
  - css/extra.css
